version: '3.8'
services:
  nginx:
    image: library/nginx:1
    container_name: portal-nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    restart: unless-stopped

  portal-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portal-app
    ports:
      - 5000:5000
      - 3000:3000
    # volume mount docker based files so that they don't rebuild on each deployment
    volumes:
    - ./docker_node_modules:/code/node_modules
    - ./docker_build:/code/build
    stdin_open: true
    restart: unless-stopped

  vouch-proxy:
    container_name: portal-vouch
    image: voucher/vouch-proxy
#    ports:
#      - 9090:9090
    volumes:
      - ./vouch:/config
    restart: unless-stopped